name: Build and push Docker images

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - Readme.md
      - build.sh

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
      push: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build env
        run: ./scripts/build-env.sh > .env.hcl
      - name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@v4
        with:
          files: docker-bake.hcl,.env.hcl
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build env
        run: ./scripts/build-env.sh > .env.hcl

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl,.env.hcl
          targets: ${{ matrix.target }}
          push: ${{ needs.prepare.outputs.push == 'true' }}
