name: Build and push Docker images

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - Readme.md
      - build.sh

env:
  PUSH_IMAGES: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout
        uses: actions/checkout@v4
      - name: Build env
        run: ./scripts/build-env.sh > .env.hcl

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl,.env.hcl
          push: ${{ env.PUSH_IMAGES == 'true' }}
